argocdのapplicationリソース追加
cloudopsdays/dreamkast-infra_codt2022 pull request #3
Opened 2022-04-09 08:22 UTC by kntks

# やったこと
- [dreamkast-infra/manifests/argocd-apps/prd/](https://github.com/cloudnativedaysjp/dreamkast-infra/tree/main/manifests/argocd-apps/prd)にあるファイルをコピー
- `repoURL`を `https://github.com/cloudopsdays/dreamkast-infra_codt2022.git`に変更

diffが大きいので、一旦ここまでMR出します

2022-04-09 08:37 UTC, ShotaKitazawa reviewed
以下は今回どうしましょう？

* grafana
* jaeger
* loki
* mysql
* prometheus
* social-analysis
* telegraf

自分の理解としては、monitoring/logging/tracing 基盤は CODT でも構築し、 mysql, social-analysis, telegraf は o11y チームのアプリケーションを動かすためのものなので (o11y チームが CODT に参画しない限り) なくて良いんじゃないかと思っています。

2022-04-09 08:38 UTC, ShotaKitazawa commented
初回構築なので、成果物は PR に出しつつどんどん作業を進めてもらって構わないです！

2022-04-17 03:06 UTC, kntks commented
mysql, social-analysis, telegraf  は確かに必要ないと思うので、削除しておきます

2022-04-17 09:51 UTC, inductor requested changes

2022-04-17 09:51 UTC, inductor commented on manifests/argocd-apps/prd/grafana.yaml
> +              url: https://raw.githubusercontent.com/cloudnativedaysjp/dreamkast-infra/01d27ac125fc2edcc6db9f8ab6f0e62149cf9952/dashboards/Contour-HTTProxy.json
このへんのリポジトリ参照するところ、直してください

2022-04-17 09:51 UTC, inductor commented on manifests/README.md
> +* [argocd/overlays/dev/argocd-cm.yaml](https://github.com/cloudnativedaysjp/dreamkast-infra/blob/main/manifests/argocd/overlays/dev/argocd-cm.yaml) にて `reviewappctl` Plugin を定義
ここら辺も直したほうがいいかな？

2022-04-17 09:51 UTC, inductor commented on manifests/README.md
> +[reviewapp-operator](https://github.com/cloudnativedaysjp/reviewapp-operator) を用いて以下のように Review Apps 環境を動的に作成している。
ここはそのままでよさそう？ @ShotaKitazawa どうすか

2022-04-17 09:51 UTC, inductor commented on manifests/README.md
> +    ├── dreamkast ... cloudnativedaysjp/dreamkast に対する Review Apps の設定
ここらへんのパスも直したほうがいいかな？（ここは確証がないので確認してください）

2022-04-17 10:32 UTC, kntks commented on manifests/argocd-apps/prd/grafana.yaml
> +              url: https://raw.githubusercontent.com/cloudnativedaysjp/dreamkast-infra/01d27ac125fc2edcc6db9f8ab6f0e62149cf9952/dashboards/Contour-HTTProxy.json
Contour-HTTProxy.json, Kubernetes-Pod を追加してURL変更しました。  

今はmainを見るようにしていますが、もしhash値を指定する場合はmergeされた後修正します。

`https://raw.githubusercontent.com/cloudopsdays/dreamkast-infra_codt2022/main`

2022-04-17 10:34 UTC, inductor commented on manifests/argocd-apps/prd/grafana.yaml
> +            role_attribute_path: contains("https://cloudnativedays.jp/roles", 'O11Y2022-Admin') && 'Admin'
ここはこのままで問題ない？

2022-04-17 10:35 UTC, inductor requested changes

2022-04-17 10:35 UTC, inductor commented on manifests/argocd-apps/prd/aws-cluster-autoscaler.yaml
> +        value: dreamkast-cluster
```suggestion
        value: dreamkast-codt-cluster
```

2022-04-17 10:35 UTC, inductor commented on manifests/argocd-apps/prd/aws-load-balancer-controller.yaml
> +        value: dreamkast-cluster
```suggestion
        value: dreamkast-codt-cluster
```

2022-04-17 10:39 UTC, kntks commented on manifests/argocd-apps/prd/grafana.yaml
> +            role_attribute_path: contains("https://cloudnativedays.jp/roles", 'O11Y2022-Admin') && 'Admin'
codt2022作り忘れてました・・

2022-04-17 10:46 UTC, kntks commented on manifests/argocd-apps/prd/grafana.yaml
> +            role_attribute_path: contains("https://cloudnativedays.jp/roles", 'O11Y2022-Admin') && 'Admin'
Auth0で "CODT2022-Admin" 作成 done

2022-04-17 10:51 UTC, kntks commented on manifests/README.md
> +    ├── dreamkast ... cloudnativedaysjp/dreamkast に対する Review Apps の設定
reviewapps周りは、 @ShotaKitazawa さんが必要ならpr出してくださるということで一旦 reviewappsの記述は消しておきます・・

2022-04-19 01:32 UTC, inductor approved these changes
やっていくか

2022-04-19 01:32 UTC, merged