argocdとinfraの追加
cloudopsdays/dreamkast-infra_codt2022 pull request #4
Opened 2022-04-10 01:08 UTC by kntks

2022-04-10 02:52 UTC, kntks commented
`aler-rules.yaml`必要ないかも

2022-04-19 01:42 UTC, inductor requested changes

2022-04-19 01:42 UTC, inductor commented on manifests/argocd/overlays/prd/argocd-cm.yaml
> +    - 'https://cloudnativedays.jp/claims/groups'
ここがどうかは要確認 @jacopen

2022-04-19 01:42 UTC, inductor commented on manifests/argocd-apps/prd/argocd-ingress.yaml
> +    targetRevision: feature/kono/add_infra_argo
これはマージすればいいので変える必要ないんじゃない

2022-04-19 01:43 UTC, kntks commented on manifests/argocd-apps/prd/argocd-ingress.yaml
> +    targetRevision: feature/kono/add_infra_argo
動作確認で変えてた部分をミスってコミットしていたやつですね。  
直します

2022-04-19 16:39 UTC, inductor commented on manifests/argocd-apps/prd/argocd-ingress.yaml
> +    targetRevision: feature/kono/add_infra_argo
```suggestion
    targetRevision: main
```

2022-04-28 02:36 UTC, merged